language: python
sudo: false
python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
env:
  matrix:
    - DJANGO=django==1.7.3
matrix:
  fast_finish: true
cache:
  directories:
    - $HOME/.pip-cache/
install:
  - travis_retry pip install $DJANGO coverage --download-cache $HOME/.pip-cache
  - pip install -e . --download-cache $HOME/.pip-cache
script: 
  - coverage run tests/manage.py test django_s3_storage
after_script:
  - coveage report
notifications:
  email: false
